install_name="docmerge"
gdrive_root ="Doc Merge"
install_display={"name":"Echo Publish for Glanty","about":["Echo Publish for Teclet.", "Please See the 'Help' page for guidance.", "You may have questions: please get in touch.", "We welcome feedback: please get in touch.", "Contact: publish@echo-central.com", "(c) Echo Central Ventures 2017"]}
local_root ="resources"
email_credentials = {"username":"", "password":"", "server":""}
email_default_recipient=""
remote_library = False
library_page = "dash/library.html"
compose_page = "dash/nocompose.html"
extend_path = False
