# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MergeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_folder', models.CharField(max_length=100)),
                ('template', models.CharField(choices=[('Library.md', 'Library.md'), ('AddParty.html', 'AddParty.html'), ('Simple.md', 'Simple.md'), ('boilerplate3.md', 'boilerplate3.md'), ('envelope.md', 'envelope.md'), ('AddParty_v3.md', 'AddParty_v3.md'), ('Tenancy_Agreement', 'Tenancy_Agreement'), ('AddParty_v2.md', 'AddParty_v2.md'), ('AddParty.md', 'AddParty.md')], max_length=100)),
                ('flow', models.CharField(max_length=100)),
                ('output_folder', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=100)),
                ('payload', models.TextField()),
                ('payload_type', models.CharField(max_length=100)),
                ('test_case', models.CharField(max_length=100)),
                ('data_folder', models.CharField(max_length=100)),
                ('data_file', models.CharField(choices=[('testData0.xml', 'testData0.xml')], max_length=100)),
                ('data_root', models.CharField(max_length=100)),
                ('branding_folder', models.CharField(max_length=100)),
                ('branding_file', models.CharField(choices=[('superll.xml', 'superll.xml'), ('nineyds.xml', 'nineyds.xml')], max_length=100)),
            ],
        ),
    ]
