# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=100)),
                ('remote', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='mergejob',
            name='template_subfolder',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mergejob',
            name='xform_file',
            field=models.CharField(choices=[('ITP_9yds_email[Conflict].xml', 'ITP_9yds_email[Conflict].xml'), ('ITP_9yds_email.xml', 'ITP_9yds_email.xml'), ('ITP_9yds_TA.xml', 'ITP_9yds_TA.xml'), ('Copy of ITP_9yds_email (1).xml', 'Copy of ITP_9yds_email (1).xml'), ('Old Copy of ITP_9yds_email.xml', 'Old Copy of ITP_9yds_email.xml')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mergejob',
            name='xform_folder',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mergejob',
            name='branding_file',
            field=models.CharField(choices=[('nineyds.xml', 'nineyds.xml')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mergejob',
            name='data_file',
            field=models.CharField(choices=[('testData25-1.xml', 'testData25-1.xml'), ('testData4.xml', 'testData4.xml'), ('testData_email2.xml', 'testData_email2.xml'), ('testData_email1.xml', 'testData_email1.xml'), ('testData3.xml', 'testData3.xml'), ('TenancyAgreement_636a7ea1-2a70-4797-9bdb-56f2c2f87528.xml', 'TenancyAgreement_636a7ea1-2a70-4797-9bdb-56f2c2f87528.xml'), ('testData2.xml', 'testData2.xml'), ('testData1.xml', 'testData1.xml'), ('testData0.xml', 'testData0.xml')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mergejob',
            name='flow',
            field=models.CharField(choices=[('comp_docx.txt', 'comp_docx.txt'), ('docx.txt', 'docx.txt'), ('txt.txt', 'txt.txt'), ('xml.txt', 'xml.txt'), ('docx_sig.txt', 'docx_sig.txt'), ('xmld.txt', 'xmld.txt'), ('pet.txt', 'pet.txt'), ('xml_dl.txt', 'xml_dl.txt'), ('docx_dl.txt', 'docx_dl.txt'), ('md.txt', 'md.txt'), ('mde.txt', 'mde.txt'), ('html.txt', 'html.txt')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mergejob',
            name='template',
            field=models.CharField(choices=[('email_9yds_envelope.xml', 'email_9yds_envelope.xml'), ('Wizard Move in documents', 'Wizard Move in documents'), ('Sandbox', 'Sandbox'), ('Wizard Emails (New)', 'Wizard Emails (New)'), ('envelope.md', 'envelope.md'), ('envelope.md', 'envelope.md'), ('envelope.md', 'envelope.md'), ('Library.md', 'Library.md')], max_length=100),
        ),
    ]
