# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20160505_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergejob',
            name='branding_file',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mergejob',
            name='data_file',
            field=models.CharField(choices=[('EchoCentral-Glanty.xml', 'EchoCentral-Glanty.xml')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mergejob',
            name='flow',
            field=models.CharField(choices=[('docx.flo', 'docx.flo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mergejob',
            name='template',
            field=models.CharField(choices=[('Contracts', 'Contracts'), ('Sandbox', 'Sandbox')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mergejob',
            name='xform_file',
            field=models.CharField(max_length=100),
        ),
    ]
