# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20160516_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergejob',
            name='data_file',
            field=models.CharField(choices=[('EchoCentral-Glanty-Invoice.xml', 'EchoCentral-Glanty-Invoice.xml'), ('EchoCentral-Glanty.xml', 'EchoCentral-Glanty.xml'), ('FS_EchoPublish.xml', 'FS_EchoPublish.xml'), ('KB_Circus.xml', 'KB_Circus.xml'), ('KB_DocBrown.xml', 'KB_DocBrown.xml'), ('KB_FOTR.xml', 'KB_FOTR.xml'), ('Knudsen_Bolts.xml', 'Knudsen_Bolts.xml'), ('liontamer.xml', 'liontamer.xml'), ('sample.xml', 'sample.xml'), ('strongman.xml', 'strongman.xml')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mergejob',
            name='flow',
            field=models.CharField(choices=[('comp_docx.flo', 'comp_docx.flo'), ('comp_docx_2.flo', 'comp_docx_2.flo'), ('comp_docx_2a.flo', 'comp_docx_2a.flo'), ('docx.flo', 'docx.flo'), ('docx_2.flo', 'docx_2.flo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mergejob',
            name='template',
            field=models.CharField(choices=[('Contracts', 'Contracts'), ('Fact Sheet - Copy.docx.zip', 'Fact Sheet - Copy.docx.zip'), ('Fact Sheet.docx', 'Fact Sheet.docx'), ('Fact Sheet.prep.docx', 'Fact Sheet.prep.docx'), ('Invoice.docx', 'Invoice.docx'), ('Invoice.docx.zip', 'Invoice.docx.zip'), ('Invoice.prep.docx', 'Invoice.prep.docx'), ('Invoices', 'Invoices'), ('Invoice_2.docx', 'Invoice_2.docx'), ('Invoice_2.prep.docx', 'Invoice_2.prep.docx'), ('Job Description.docx', 'Job Description.docx'), ('Job Description.prep.docx', 'Job Description.prep.docx'), ('nutsnbolts.png', 'nutsnbolts.png'), ('Sample Document.docx', 'Sample Document.docx'), ('Sample Document.prep.docx', 'Sample Document.prep.docx'), ('Sandbox', 'Sandbox')], max_length=100),
        ),
    ]
