# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-22 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_auto_20170201_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_folder', models.CharField(max_length=100)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_content', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComposeTemplate',
            fields=[
                ('editfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dash.EditFile')),
                ('template_subfolder', models.CharField(choices=[('--', '--')], max_length=100)),
                ('template_files', models.CharField(blank=True, choices=[('--', '--')], max_length=100, null=True)),
                ('template_test_case', models.CharField(blank=True, choices=[('--', '--')], max_length=100, null=True)),
                ('test_case_xform', models.CharField(blank=True, choices=[('--', '--')], max_length=100, null=True)),
                ('template_stylesheet', models.CharField(blank=True, choices=[('--', '--')], max_length=100, null=True)),
                ('template_stylesheet_content', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            bases=('dash.editfile',),
        ),
    ]
